spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/book_manager
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
